### PR TITLE
Fix conflicts for szlazure/joomla.sql

### PR DESCRIPTION
**Pull request by richard67**

### CODE REVIEW

**Comment by richard67** [comment]
@alikon Strange, the conflicts seems to be solved already, so my PR here which I made for helping with the conflicts corrects only a bit spacing. Maybe you just have to mark the conflicts as solved in Git?

**Comment by alikon** [comment]
really really strange  still have conflicts.... aaarrgggghhh

**Comment by richard67** [comment]
The diff between my PR and your branch looks OK, only the diff between your PR and staging shows the conflicts. Maybe just appveyor has hung up or travis or something like that?

**Comment by richard67** [comment]
maybe just redo your PR with a new one.

**Comment by alikon** [comment]
yes if i don't get some hepls from github guru

**Comment by richard67** [comment]
Anyway this PR is useful because it makes spacing same as for the other statements of this type. Maybe it will also unblock this "has conflicts" situation if you merge my PR?

**Comment by richard67** [comment]
Or maybe check this one:
[https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)

**Comment by richard67** [comment]
Maybe this helps:

1. Save your changed sqlazure/joomla.sql file somewhere.
2. In Git for windows client, select your repository joomla_cms, then select your branch patch-69 of your joomla_cms repository, then open Git Shell using the context menu "Open in Git Shell" of the joomla_cms repository in the repository list.
3. Check that the Git Shell shows the correct branch patch-69 in its prompt.
4. Do following commands to reset all changes in the file:
```
cd installation\sql\sqlazure
git checkout -- joomla.sql
```
5. Still in the same Git shell window on the same branch: Rebase your branch to current staging:
```
git fetch upstream
git rebase upstream/staging
git push origin patch-69 --force
```
6. Now you can edit it again. Copy your changes from the file saved with step1 into the joomla.sql (which now is current staging) and if necessary adapt the change to the format of the rest of the file (spacing, maybe names quoting).
7. Commit your changes.

Now all should be fine.

**Comment by alikon** [comment]
thanks for the help 
conflicts are solved now https://github.com/joomla/joomla-cms/pull/10739

**Pull request closed without merging**
