### PR TITLE
go to the right tab

### PR DESCRIPTION
**Pull request by dgt41**
This change is [Reviewable](https://reviewable.io/reviews/alikon/joomla-cms/26)

### CODE REVIEW

**Comment by alikon** [comment]
@dgt41 it did'nt work

system -> global configuration -> and click on permissions tab
then
system -> control panel -> statistics module and click on Caching
you are redirected to the permissions tab instead of system tab

**Comment by dgt41** [comment]
@alikon it works fine for me, maybe you need to empty your localStorage

**Comment by alikon** [comment]
i'll retest, maybe i used the wrong clean i'm staring to use Opera ;)

if i follow this one https://github.com/joomla/joomla-cms/pull/13396#pullrequestreview-14778556
do you need to change the js also isn't it ?

**Comment by dgt41** [comment]
Let me test that

**Comment by alikon** [comment]
sure take your time....

**Comment by dgt41** [comment]
@alikon works fine with the `Route()` as well

**Comment by alikon** [comment]
i've tested unsuccessfully on Chrome too
before to click on Caching disabled
before
after
after

it seems that don't work if you run on subfolder  like me  my site root is htdocs/issue/

if i hardcode the issue folder than works
hardcode

@dgt41 can you investigate ?

**Comment by dgt41** [comment]
@alikon can you check?

**Comment by alikon** [comment]
perfect 
thanks @dgt41

**Pull request merged**
