### PR TITLE
Patch 117 patch pr 31379

### PR DESCRIPTION
**Pull request by pjdevries**
### Summary of Changes

- Added global config settings for `Access-Control-Allow-Origin`, `Access-Control-Allow-Headers` and `Access-Control-Allow-Methods`.
- Added preflight handler method to `Joomla\CMS\Application\ApiApplication`.
- Made some changes to  `Joomla\CMS\Application\ApiApplication` and `Joomla\CMS\Router\Router` needed for implementation of  the preflight handler.
- Removed obsolete code from the  `Joomla\CMS\Application\ApiApplication` respond method.

### CODE REVIEW

**Comment by alikon** [comment]
Thank you @pjdevries 
i've just read the code diff and it seems  good to me....
i've currently no time to test it and/or to deep check this comment
https://github.com/joomla/joomla-cms/pull/31379#discussion_r522398964

but let's merge it  so we can have a more broad feedback

**Comment by pjdevries** [comment]
Thanx. Nice to see you appreciate the modifications.

**Comment by alikon** [comment]
testing.....
just made a small fix https://github.com/joomla/joomla-cms/pull/31379/commits/1bf09d4c902e5b82e8f3acbf16c943c3e79c7123

**Comment by pjdevries** [comment]
Apologies for the sloppiness.

**Comment by alikon** [comment]
no problem i'm going to fix some small cs ....

**Comment by alikon** [comment]
cs fixed now

**Comment by alikon** [comment]
... and pinged the few people that i know that are on this matter:
@wilsonge 
@razzo1987
@zero-24

if you know someone else....

**Comment by pjdevries** [comment]
The only one I can think of, is @roland-d.

**Pull request merged**
